### ISSUE TITLE
Research if cookies are the right answer

### ISSUE THREAD

**Issue by mpetrimoulx** [kchambers54/spotify-companion#8]
Can we use cookies to give the user their token so that they control their own data?

**Comment by kchambers54** [comment]
I was doing some reading and it looks like we want to store these tokens on the backend.  It's the same as Discord keeping your token when you link spotify so that you don't need to sign in again.
https://stackoverflow.com/questions/29400426/where-do-i-persist-the-spotify-access-token

**Comment by kchambers54** [comment]
It looks like utilizing session variables makes the most sense here.  Flask technically stores session variables on the client-side, so we may want to readdress this later for security reasons.  It's fine for users to have their access tokens, but sending them to the client may be a bad idea?
